### ISSUE TITLE
Feld nach Form-Fehler disabled

### ISSUE THREAD

**Issue by cmartin6** [terminal42/contao-conditionalformfields#72]
Bei fehlerhaften Absenden eines Formulars mit Radio-Button Feld-Toggle ist das "andere" Feld _disabled_.

https://user-images.githubusercontent.com/47104009/214505365-894cb8f1-171e-4773-b4ee-7a30cd2e7a8e.mov

**Comment by aschempp** [comment]
Fixed in 78f680d63f02a2652ca7fc93f0fc0d63f8ddc712. This originated in https://github.com/terminal42/contao-conditionalformfields/pull/18 because hidden fields must not submit their input. But conditionalformfields v3 no longer set fields to enabled or disabled, since disabling a fieldset automatically does that anyway.
